name: CI/CD Frontend + Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ---------- FRONTEND TEST ----------
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test

    # ---------- BACKEND TEST ----------
    - name: Setup Backend (example: Python)
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Backend Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run Backend Tests
      run: |
        cd backend
        pytest  # or your test command

    # ---------- DOCKER LOGIN ----------
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: docker/login-action@v2
      with:
        registry: amsregistry1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # ---------- BUILD & PUSH FRONTEND ----------
    - name: Build Frontend Docker Image
      run: docker build -t amsregistry1.azurecr.io/frontend:latest ./frontend

    - name: Push Frontend Docker Image
      run: docker push amsregistry1.azurecr.io/frontend:latest

    # ---------- BUILD & PUSH BACKEND ----------
    - name: Build Backend Docker Image
      run: docker build -t amsregistry1.azurecr.io/backend:latest ./backend

    - name: Push Backend Docker Image
      run: docker push amsregistry1.azurecr.io/backend:latest
